In [1]:
import os

print(os.getcwd())

C:\Users\sugit\OneDrive\Tài liệu\KG_Ontology_Project\notebooks

In [2]:
import os

print(os.listdir("../"))

['dataset', 'modules', 'notebooks', 'results', 'rules']

In [3]:
import os

print(os.listdir("../dataset"))

['test.txt', 'train.txt', 'valid.txt']

In [4]:
import pandas as pd

train = pd.read_csv(
    "../dataset/train.txt",
    sep="\t",
    header=None,
    names=["head", "relation", "tail"]
)

train.head()

         head                                           relation       tail
0    /m/027rn               /location/country/form_of_government   /m/06cx9
1   /m/017dcd  /tv/tv_program/regular_cast./tv/regular_tv_app...  /m/06v8s0
2  /m/07s9rl0                 /media_common/netflix_genre/titles  /m/0170z3
3   /m/01sl1q  /award/award_winner/awards_won./award/award_ho...  /m/044mz_
4   /m/0cnk2q  /soccer/football_team/current_roster./sports/s...  /m/02nzb8

In [5]:
print("Number of triples:", len(train))

entities = set(train["head"]) | set(train["tail"])

print("Number of unique entities:", len(entities))

print("Number of unique relations:", train["relation"].nunique())

Number of triples: 272115
Number of unique entities: 14505
Number of unique relations: 237

In [6]:
train["relation"].value_counts()

relation
/award/award_nominee/award_nominations./award/award_nomination/award_nominee                        15989
/film/film/release_date_s./film/film_regional_release_date/film_release_region                      12893
/award/award_nominee/award_nominations./award/award_nomination/award                                12157
/people/person/profession                                                                           10945
/film/actor/film./film/performance/film                                                              9494
                                                                                                    ...
/user/alexander/philosophy/philosopher/interests                                                      100
/dataworld/gardening_hint/split_to                                                                     99
/film/special_film_performance_type/film_performance_type./film/performance/film                       93
/tv/non_character_role/tv_regular_personal_appearances./tv/tv_regular_personal_appearance/person       90
/film/person_or_entity_appearing_in_film/films./film/personal_film_appearance/type_of_appearance       37
Name: count, Length: 237, dtype: int64

In [7]:
profession_triples = train[
    train["relation"] == "/people/person/profession"
]

profession_triples.head(10)

           head                   relation        tail
21     /m/0grwj  /people/person/profession   /m/05sxg2
31    /m/053y0s  /people/person/profession    /m/0dz3r
70     /m/0411q  /people/person/profession   /m/016z4k
117    /m/02g8h  /people/person/profession   /m/01d_h8
126   /m/042l3v  /people/person/profession   /m/01d_h8
133    /m/0hl3d  /people/person/profession    /m/0cbd2
215    /m/06cv1  /people/person/profession   /m/02jknp
237  /m/01nqfh_  /people/person/profession   /m/01c8w0
288    /m/0kzy0  /people/person/profession    /m/0gbbt
368    /m/03_gd  /people/person/profession  /m/07s467s

In [8]:
film_triples = train[
    train["relation"] == "/film/actor/film./film/performance/film"
]

film_triples.head(10)

          head                                 relation       tail
6    /m/07nznf  /film/actor/film./film/performance/film  /m/014lc_
17    /m/079vf  /film/actor/film./film/performance/film   /m/0d90m
38   /m/012d40  /film/actor/film./film/performance/film  /m/034qmv
54   /m/04yywz  /film/actor/film./film/performance/film  /m/0140g4
57   /m/06688p  /film/actor/film./film/performance/film  /m/0b2v79
91    /m/06dv3  /film/actor/film./film/performance/film  /m/09m6kg
111  /m/049tjg  /film/actor/film./film/performance/film  /m/05jf85
144  /m/023tp8  /film/actor/film./film/performance/film  /m/0dq626
158   /m/09fb5  /film/actor/film./film/performance/film  /m/07xtqq
173  /m/032xhg  /film/actor/film./film/performance/film  /m/034qrh

In [9]:
print("Profession triples:", len(profession_triples))
print("Film triples:", len(film_triples))

Profession triples: 10945
Film triples: 9494

In [10]:
print("Unique heads:", profession_triples["head"].nunique())
print("Unique tails:", profession_triples["tail"].nunique())

Unique heads: 4123
Unique tails: 149

In [11]:
profession_triples["tail"].value_counts().head(10)

tail
/m/02hrh1q    2264
/m/0dxtg       872
/m/01d_h8      863
/m/02jknp      602
/m/03gjzk      575
/m/09jwl       574
/m/0cbd2       435
/m/0nbcg       380
/m/0np9r       346
/m/0dz3r       291
Name: count, dtype: int64

In [12]:
print("Total profession triples:", len(profession_triples))
print("Unique people/entities:", profession_triples["head"].nunique())
print("Unique professions/entities:", profession_triples["tail"].nunique())

Total profession triples: 10945
Unique people/entities: 4123
Unique professions/entities: 149

In [13]:
valid = pd.read_csv(
    "../dataset/valid.txt",
    sep="\t",
    header=None,
    names=["head", "relation", "tail"]
)

test = pd.read_csv(
    "../dataset/test.txt",
    sep="\t",
    header=None,
    names=["head", "relation", "tail"]
)

print("Validation triples:", len(valid))
print("Test triples:", len(test))

Validation triples: 17535
Test triples: 20466